- hosts: all

  tasks:
    - name: apt-get update
      apt:
        update_cache: yes

    - name: instalamos paquetes
      apt: pkg={{ item }} state=latest
      with_items:
      - apt-transport-https 
      - ca-certificates 
      - curl 
      - gnupg-agent 
      - software-properties-common 
    
    - name: shell docker1
      become: true
      become_user: root
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    
    - name: shell docker2 repositorios
      become: true
      become_user: root
      shell: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

    - name: apt-get update
      apt:
        update_cache: yes
 
    - name: instalamos paquetes docker
      apt: pkg={{ item }} state=latest
      with_items:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
